[project]
name = "bdhackathon"
version = "0.1.0"
description = "banco de dados hackathon"
authors = [
    {name = "Gabriel", email = "gabrielviniciuscorrea204@gmail.com"},
]
dependencies = [
    "django>=5.1.2",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
